### ISSUE TITLE
Cloudera Manager Lab

### ISSUE THREAD

**Issue by mustafatok** [mustafatok/SEBC#5]

**Comment by mustafatok** [comment]
Hue was not accessible after upgrade! When i wanted to try logging in I was getting BAD REQUEST error on web-page. 

Here is how I solved it:
I put 
```
[desktop]
allowed_hosts=*
```
inside "Hue Service Advanced Configuration Snippet (Safety Valve) for hue_safety_valve.ini"

**Comment by mfernest** [comment]
I'm curious how this problem crops up so infrequently. I would guess it has to do with the way people manage their `/etc/hosts` file
